Convertig list of date and time placeholder into table
CIDRAM/CIDRAM pull request #95
Opened 2018-10-01 17:28 UTC by frommMoritz

2018-10-02 00:01 UTC, Maikuolan commented
@frommMoritz : Nice idea, and thanks for the contribution! This should help users to better understand the placeholders, I think. :+1: 😊

I'll leave this PR open for a few hours or so in case anyone has any comments, and otherwise will merge after that.

( @DanielRuf : If you've got a spare moment, could you check the spelling and grammar for the changed lines? Cheers. 😊 )

2018-10-02 04:54 UTC, DanielRuf commented
Will do so.

2018-10-06 19:33 UTC, DanielRuf requested changes

2018-10-06 19:33 UTC, DanielRuf commented on _docs/readme.de.md
> +- Name einer Datei in welcher serialisiert alle blokierten zugriffsversuche Protokolliert werden. Geben Sie einen Dateinamen an oder lassen Sie die Option zum Deaktivieren leer.
zugriffsversuche => Zugriffsversuche
Protokolliert => protokolliert
Deaktivieren => deaktivieren

2018-10-06 19:33 UTC, DanielRuf commented on _docs/readme.de.md
> +*Nützlicher Tipp: Wenn Sie wollen, können Sie Datum/Uhrzeit-Information im Namen der Protokolldateien verwenend.*
verwenend => verwenden

2018-10-06 19:33 UTC, DanielRuf commented on _docs/readme.de.md
> +`{yyyy}`|Komplettes  Jahr|2018
Komplettes => komplettes

2018-10-06 19:33 UTC, DanielRuf commented on _docs/readme.de.md
> +`{yy}`|Abgekürtztes Jahr|18
Abgekürtztes => abgekürztes

2018-10-06 19:33 UTC, DanielRuf commented on _docs/readme.en.md
> +`{yyyy}`|Entire Year|2018
Entire => entire
Year => year

2018-10-06 19:33 UTC, DanielRuf commented on _docs/readme.en.md
> +`{yy}`|Shortened Year|18
Shortened => shortened
Year => year

2018-10-06 19:33 UTC, DanielRuf commented on _docs/readme.en.md
> +`{yy}`|Shortened Year|18
We should check for lowercase / capitalized and not mi these.

2018-10-07 12:03 UTC, DanielRuf requested changes

2018-10-07 12:03 UTC, DanielRuf commented on _docs/readme.de.md
> +*Beispielen:*
Beispielen => Beispiele

2018-10-07 12:03 UTC, DanielRuf commented on _docs/readme.de.md
> +*Nützlicher Tipp: Wenn du willst, Sie können Datum/Uhrzeit-Information den Namen der Protokolldateien anhängen, durch diese im Namen einschließlich: `{yyyy}` für die komplette Jahr, `{yy}` für abgekü
Totally incorrect wordings, please check again.

2018-10-28 15:03 UTC, Maikuolan commented
Because English and German translations are now separated into two distinct pull requests, and this pull request now contains only the changes to the English README, and because the requested changes to the English version are relatively quick and easy to fix (correct capitalisation, etc), I'll go ahead and merge this now (I can fix the capitalisation myself a little later tonight).

2018-10-28 15:05 UTC, Maikuolan commented
*Note: Requested changes for the German README are still relevant, but apply now to #96.*

2018-10-28 15:06 UTC, merged